# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yeogidam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yeogidam
  pod 'Alamofire'

  target 'yeogidamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yeogidamUITests' do
    # Pods for testing
  end

end
